# Generated by Django 3.2.9 on 2022-03-03 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('TRIS', 'Técnico em Registros e Informações em Saúde'), ('TENF', 'Tecnico em Enfermagem '), ('VISAU', 'Técnico em Vigilância em Saúde'), ('MASSO', 'Tecnico em Massoterapia'), ('TACS', 'Técnico Agente Comunitário em Saúde'), ('GH', 'Gestão Hospitalar'), ('MP', 'Mestrado Profissional')], default='TRIS', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('carga_horaria', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.curso')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=10)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('carga_horaria_alocada', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Equalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField(default=0)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.disciplina')),
                ('periodoLetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.periodoletivo')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.turma')),
            ],
        ),
    ]
